<?php
/**
 * meetme Translations
 */

$L = [
    'bd' => [
        'title' => 'Meet Märci – Wenn hesch Zyt?',
        'subtitle' => 'Suech dr eine us.',
        'next_slots' => 'Die nächstä Termine',
        'request_slot' => 'Dä Termin afrage…',
        'name' => 'Name',
        'email' => 'E-Mail',
        'message' => 'Nachricht',
        'submit_request' => 'Aafraag schicke',
        'submit_booking' => 'Abmache',
        'slot_taken' => 'Sorry, dä Slot isch grad vo öppere anderem buechet worde… nimm bitte än andere!',
        'booking_success' => 'Super, buechet!',
        'booking_confirmation' => 'Du überchunnsch gad no ä Iladig per Mail.',
        'invite_greeting' => 'Sälü!',
        'cooldown_message' => 'Du häsch scho vor churzem buechet — mir gsehn üs am %s!',
        'no_slots' => 'Oh no… isch dr Märci mau wieder ds beschäftigte... Leider keni freie Slots ume…',
        'preferred_around' => 'Am liebschtä ir Umgäbig %s',
        'lunch' => 'Zmittag',
        'dinner' => 'Znacht',
        'meeting_with' => '%s mit %s',
        'note' => 'Notiz (optional)',
        'back' => 'Zrügg',
        'rate_limit_exceeded' => 'Grad chli viu Afrage uf einisch. Probier es später nomau.',
        'invalid_email' => 'Dini E-Mail-Adrässe gseht irgendwie nid ganz richtig us.',
        'required_fields' => 'Bitte füu aui Fäuder us.',
    ],
    'de' => [
        'title' => 'Meet Märci - Wann hast du Zeit?',
        'subtitle' => 'Such dir etwas aus.',
        'next_slots' => 'Die nächsten Termine',
        'request_slot' => 'Slot anfragen',
        'name' => 'Name',
        'email' => 'Email',
        'message' => 'Nachricht',
        'submit_request' => 'Anfrage senden',
        'submit_booking' => 'Buchen',
        'slot_taken' => 'Sorry, dieser Slot wurde gerade von jemand anderem gebucht… bitte wähle einen anderen!',
        'booking_success' => 'Super, gebucht!',
        'booking_confirmation' => 'Du solltest gleich eine Bestätigung per Mail erhalten.',
        'invite_greeting' => 'Hallo!',
        'cooldown_message' => 'Du hast bereits vor kurzem gebucht — wir sehen uns am %s!',
        'no_slots' => 'Momentan gibt es leider keine freien Slots.',
        'preferred_around' => 'Am liebsten bei %s',
        'lunch' => 'Mittagessen',
        'dinner' => 'Abendessen',
        'meeting_with' => '%s mit %s',
        'note' => 'Notiz (optional)',
        'back' => 'Zurück',
        'rate_limit_exceeded' => 'Zu viele Anfragen. Bitte versuche es später noch einmal.',
        'invalid_email' => 'Deine Email-Adresse scheint nicht korrekt zu sein.',
        'required_fields' => 'Bitte fülle alle Felder aus.',
    ],
    'en' => [
        'title' => 'Meet Märci - When shall we meet?',
        'subtitle' => 'Pick a slot.',
        'next_slots' => 'Next available slots',
        'request_slot' => 'Request a slot',
        'name' => 'Name',
        'email' => 'Email',
        'message' => 'Message',
        'submit_request' => 'Send Request',
        'submit_booking' => 'Book',
        'slot_taken' => 'Sorry, this slot was just taken by someone else… please pick another one!',
        'booking_success' => 'Great, booked!',
        'booking_confirmation' => 'You should receive a confirmation email shortly.',
        'invite_greeting' => 'Hi!',
        'cooldown_message' => "You've already booked recently — see you on %s!",
        'no_slots' => 'Currently there are no free slots available.',
        'preferred_around' => 'Preferred around %s',
        'lunch' => 'Lunch',
        'dinner' => 'Dinner',
        'meeting_with' => '%s with %s',
        'note' => 'Note (optional)',
        'back' => 'Back',
        'rate_limit_exceeded' => 'Too many requests. Please try again later.',
        'invalid_email' => 'Your email address doesn\'t look right.',
        'required_fields' => 'Please fill in all fields.',
    ],
];
